services:
  db:
    image: postgres
    container_name: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports: 
      - "5432:5432"
    networks:
      - trans_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "8888:80"
    depends_on:
      - db
    networks:
      - trans_network


  backend:
    build: ./src/backend
    container_name: backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - trans_network
    volumes:
      - ./src/backend:/app
      - .env:/app/.env
    depends_on:
      - db
      - redis 
    

  frontend:
    container_name: frontend
    build: ./src/frontend
    ports:
      - "3000:80"
    networks:
      - trans_network
    volumes:
      - ./src/frontend:/app


  redis:
    image: redis
    container_name: redis
    ports:
      - "6378:6379"
    networks:
      - trans_network


networks:
  trans_network:
    driver: bridge